Repository TkinterEP/ttkwidgets, pull requests merged in 2021-02, with the labels that each got.

#44 Merge tooltips into master to add hooks and tooltip kwargs
  AUTHORS.md
  docs/source/ttkwidgets/ttkwidgets.rst
  docs/source/ttkwidgets/ttkwidgets/ttkwidgets.hook.rst
  docs/source/ttkwidgets/ttkwidgets/ttkwidgets.tooltips.rst
  examples/example_hook.py
  examples/example_tooltips.py
  tests/test_hooks.py
  tests/test_scaleentry.py
  tests/test_table.py
  tests/test_tooltips.py
  ttkwidgets/frames/__init__.py
  ttkwidgets/hook.py
  ttkwidgets/tooltips.py
Labels: enhancement

#72 Merge readme into master for fixes to README.md
  .appveyor.yml
  .travis.yml
  README.md
  setup.py
Labels: repo

#58 Merge validated-entry into master to add ValidatedEntry widget
  AUTHORS.md
  docs/source/authors.rst
  docs/source/documentation.rst
  docs/source/ttkwidgets/ttkwidgets.validated_entries.rst
  docs/source/ttkwidgets/ttkwidgets.validated_entries/ttkwidgets.validated_entries.numbers.rst
  docs/source/ttkwidgets/ttkwidgets.validated_entries/ttkwidgets.validated_entries.strings.rst
  docs/source/ttkwidgets/ttkwidgets.validated_entries/ttkwidgets.validated_entries.validated_entry.rst
  docs/source/ttkwidgets/ttkwidgets.validated_entries/ttkwidgets.validated_entries.validators.rst
  examples/example_validated_entries.py
  tests/test_utilities.py
  tests/test_validatedentries.py
  ttkwidgets/__init__.py
  ttkwidgets/utilities.py
  ttkwidgets/validated_entries/__init__.py
  ttkwidgets/validated_entries/numbers.py
  ttkwidgets/validated_entries/strings.py
  ttkwidgets/validated_entries/validated_entry.py
  ttkwidgets/validated_entries/validators.py
Labels: enhancement, widget
